In [6]:
weight_kg = int(input("Enter your weight in KG: \n"))
height_cm = int(input("Enter your height in cm: \n"))
age = int(input("Enter your age in years: \n"))
isMale = str(input("Are you male? (y/n)"))
activity = input("How active are you? 1 for sedentary, 2 for lightly active, 3 for moderately active, 4 for very active, and 5 for extremely active: ")
goal_weight = float(input("Enter your goal weight in pounds: "))
calories_consumed_per_day = float(input("Enter the number of calories consumed per day: "))

weight_pounds = weight_kg * 2.205
height_inches = height_cm / 2.54

if isMale == "y":
    isMale = True
elif isMale == "n":
    isMale = False
else:
    print("Error")
    quit()

# Bmr: Basal Metabolic Rate: number of calories you burn as your
#  body performs basic (basal) life-sustaining function
#https://www.garnethealth.org/news/basal-metabolic-rate-calculator#:~:text=Your%20basal%20metabolism%20rate%20is,4.330%20x%20age%20in%20years)
def calcBmrHB(): #checked function 
    if isMale:
        bmr =  88.362 + (13.397 * weight_kg) + (4.799 * height_cm) - (5.677 * age)

    else:
        bmr = 447.593 + (9.247 * weight_kg) + (3.098 * height_cm) - (4.330 * age)        
    bmr = round(bmr)
    return(bmr) 

# bmi: body mass index 
def BMI(): #DONE CHECKING FUNCTION 
    bmi = weight_pounds / pow(height_inches,2)*703
    return round(bmi,1)

# # Obesity class 
bmi = BMI()
print(bmi,"bmi")
def obesity_class(bmi):
    if bmi<16:
        obesity= 'Severely Underweight'
    elif bmi<18.5:
        obesity=  'Underweight'
    elif bmi<25.1:
        obesity=  'Normal Weight'
    elif bmi<30.1:
        obesity=  'Overweight'
    elif bmi<35.1:
        obesity=  "Class I Obesity"
    elif bmi<40:
        obesity=  "Class II Obesity"
    elif bmi<50:
        obesity=  "Class III Obesity"
    elif bmi<60:
        obesity=  'Class IV Obesity'
    else :
        obesity=  'Class V Obesity'
    return obesity

#standardized version: to lose 1 pound, one needs to cut down 3500 calories in total
CALORIES_PER_POUND = 3500


harrisBMR = calcBmrHB()
print(harrisBMR,"BMR")
def TDEE(harrisBMR):
    if activity == str(1):
        total = harrisBMR * 1.2
    elif activity == str(2):
        total = harrisBMR * 1.375
    elif activity == str(3):
        total = harrisBMR * 1.55
    elif activity == str(4):
        total = harrisBMR * 1.725
    elif activity == str(5):
        total = harrisBMR * 1.9
    return total

daily_calorie_needs = TDEE(harrisBMR)
print(daily_calorie_needs,"goal calorie per day")
# Calculations
def day_to_reach_goal_weight():
    print(weight_pounds,"your weight in pounds")
    weight_to_lose = goal_weight - weight_pounds
    print(weight_to_lose,"weight to lose (in pounds)")
    calories_needed_to_lose_weight = weight_to_lose * CALORIES_PER_POUND
    print(calories_needed_to_lose_weight,"calories_needed_to_lose_weight")
    calorie_deficit_per_day = daily_calorie_needs - calories_consumed_per_day
    
    print(calorie_deficit_per_day,"calorie_deficit_per_day")
    days_to_reach_goal_weight = calories_needed_to_lose_weight / calorie_deficit_per_day
    return calorie_deficit_per_day,days_to_reach_goal_weight
# Output
output = day_to_reach_goal_weight()
print(f"It will take " + str(round(output[1],2)) + " days to reach your goal weight if you eat " + str(round(output[0])) + " less calories than your current consumption")

Enter your weight in KG:
 60
Enter your height in cm:
 152
Enter your age in years:
 21
Are you male? (y/n) n
How active are you? 1 for sedentary, 2 for lightly active, 3 for moderately active, 4 for very active, and 5 for extremely active:  1
Enter your goal weight in pounds:  120
Enter the number of calories consumed per day:  2000

26.0 bmi
1382 BMR
1658.3999999999999 goal calorie per day
132.3 your weight in pounds
-12.300000000000011 weight to lose (in pounds)
-43050.00000000004 calories_needed_to_lose_weight
-341.60000000000014 calorie_deficit_per_day
It will take 126.02 days to reach your goal weight if you eat -342 less calories than your current consumption

In [1]:
import pandas as pd

In [36]:
df = pd.read_csv("main_nutrients.csv")

In [37]:
df

,Unnamed: 0.1,Unnamed: 0,Category,Age,Start_Age,End_Age,Weight (kg ),Energy (kcal ),Carbohydrates(g),Protein (g ),Vitamin A (RE ),Vitamin D (ug ),Iron (mg ),lodine (ug ),Zinc (mg ),TOTAL WATER (L /d )
0,0,0,Infants,0-1,0,1,7.3,820,205.00,12.00,350,10.0,15.0,50,15,0.8
1,1,1,Infants,1-3,1,3,11.9,1250,312.50,23.00,400,10.0,20.0,90,15,1.3
2,2,2,Infants,3-5,3,5,15.9,1510,377.50,26.00,400,8.3,20.0,90,15,1.7
3,3,3,Infants,5-7,5,7,19.6,1710,427.50,30.00,400,4.2,20.0,90,15,2.4
4,4,4,Infants,7-10,7,10,25.9,1880,470.00,38.00,400,2.5,25.0,120,15,3.3
5,5,5,Children (boys ),10-12,10,12,34.0,2170,542.50,50.00,500,2.5,35.0,120,15,3.7
6,6,6,Children (boys ),12-14,12,14,43.2,2360,590.00,NaN,6:00,2.5,3.5,150,15,3.7
7,7,7,Children (boys ),14-16,14,16,54.5,2620,655.00,75.00,600,2.5,30.0,150,15,3.7
8,8,8,Children (boys ),16-19,16,19,63.6,2820,705.00,84.00,600,2.5,30.0,150,15,3.7
9,9,9,Children (girls ),10-12,10,12,35.4,1925,481.25,52.00,500,2.5,30.0,120,15,2.1
10,10,10,Children (girls ),12-14,12,14,NaN,2040,510.00,62.00,600,2.5,30.0,150,15,2.3
11,11,11,Children (girls ),14-16,14,16,51.5,2135,533.75,69.00,5.5,2.5,NaN,150,15,2.7
12,12,12,Children (girls ),16-19,16,19,54.6,2150,537.50,66.00,500,2.5,20.0,150,15,2.7
13,13,13,Men,20-40,20,40,55.0,2550,637.50,0.57,750,2.5,20.0,150,15,2.7
14,14,14,Women,20-40,20,40,46.0,2160,540.00,0.52,750,2.5,30.0,150,20,2.7

In [34]:
def carbs_intake(gender, age):
    ans = 0
    a =  df.loc[df['Category'] == gender]
    for index, row in a.iterrows():
        if int(age) > int(row['Start_Age']) and int(age) <= int(row['End_Age']):
            ans = row['Carbohydrates(g)']
    return ans
print("Carbs (g) required:", carbs_intake("Women", 30), "(g)")

Carbs (g) required: 540.0 (g)

In [33]:
def protein_intake(gender, age):
    ans = 0
    a =  df.loc[df['Category'] == gender]
    for index, row in a.iterrows():
        if int(age) > int(row['Start_Age']) and int(age) <= int(row['End_Age']):
            ans = row['Protein (g )']
    return ans
print("Protein (g) required:", protein_intake("Women", 30), "(g)")

Protein (g) required: 0.52 (g)

In [32]:
def Calories_intake(gender, age):
    ans = 0
    a =  df.loc[df['Category'] == gender]
    for index, row in a.iterrows():
        if int(age) > int(row['Start_Age']) and int(age) <= int(row['End_Age']):
            ans = row['Energy (kcal )']
    return ans
print("Calories (kcal ) required:", Calories_intake("Women", 30), "(kcal )")

Calories (kcal ) required: 2160 (kcal )

In [35]:
def water_intake(gender, age):
    ans = 0
    a =  df.loc[df['Category'] == gender]
    for index, row in a.iterrows():
        if int(age) > int(row['Start_Age']) and int(age) <= int(row['End_Age']):
            ans = row['TOTAL WATER (L /d )']
    return ans
print("Water required:", water_intake("Women", 30), "(L /d )")

Water required: 2.7 (L /d )